In [19]:
# PASSO 1 - Carregar dados
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pickle

df = pd.read_csv('../Dataset/obesity.csv')

# PASSO 2 - Separar X e y (sem Weight e Height)
X = df.drop(columns=['Weight', 'Height', 'Obesity'])  # 'Obesity' é o target
y = df['Obesity']

# PASSO 3 - Codificar categóricas
# Identificar colunas categóricas (object dtype)
cat_cols = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X, columns=cat_cols, drop_first=True)

# PASSO 4 - Dividir treino/teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# PASSO 5 - Treinar modelo
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# PASSO 6 - Avaliar
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Acurácia: {accuracy:.4f}')
print('Matriz de confusão:')
print(confusion_matrix(y_test, y_pred))
print('Relatório de classificação:')
print(classification_report(y_test, y_pred))

# PASSO 7 - Salvar modelo e pipeline
# Salvar modelo como pickle
with open('modelo.pkl', 'wb') as f:
    pickle.dump(model, f)

# Pipeline simples
pipeline = {
    'model': model,
    'features': X.columns.tolist()
}
with open('pipeline.pkl', 'wb') as f:
    pickle.dump(pipeline, f)

print('Modelo e pipeline salvos com sucesso!')

Acurácia: 0.8463
Matriz de confusão:
[[51  2  0  0  0  3  0]
 [ 4 46  3  1  0  7  1]
 [ 0  6 67  4  0  0  1]
 [ 0  3  1 54  0  0  0]
 [ 0  0  0  0 63  0  0]
 [ 0 11  2  2  0 40  1]
 [ 1  2  4  3  0  3 37]]
Relatório de classificação:
                     precision    recall  f1-score   support

Insufficient_Weight       0.91      0.91      0.91        56
      Normal_Weight       0.66      0.74      0.70        62
     Obesity_Type_I       0.87      0.86      0.86        78
    Obesity_Type_II       0.84      0.93      0.89        58
   Obesity_Type_III       1.00      1.00      1.00        63
 Overweight_Level_I       0.75      0.71      0.73        56
Overweight_Level_II       0.93      0.74      0.82        50

           accuracy                           0.85       423
          macro avg       0.85      0.84      0.84       423
       weighted avg       0.85      0.85      0.85       423

Modelo e pipeline salvos com sucesso!
